# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools

module Constants
  MY_XCODE_WORKSPACE_FILEPATH = File.absolute_path('../MyTestApp.xcworkspace')
  MY_XCODE_TARGET_DEVICE_NAME = ENV['XCODE_TARGET_DEVICE_NAME']  # ex: "Ios automation iPhone K4982"
  MY_XCODE_TARGET_TESTS = ENV.has_key?('XCODE_TARGET_TESTS') ? ENV['XCODE_TARGET_TESTS'].split(",") : 'unused'
  MY_TRY_ATTEMPTS = 2
end



platform :ios do
  # Runs SwiftLint on our codebase
  lane :lint do
    Dir.mkdir '../fastlane/lint' unless Dir.exist? '../fastlane/lint'
    swiftlint(
      mode: :lint,
      executable: "Pods/SwiftLint/swiftlint",
      output_file: "fastlane/lint/swiftlint.result.xml",
      reporter: "junit"
    )
  end

  # Runs iOS Unit tests
  lane :simulator_unit_tests do
    simulator_unit_tests(
      workspace: Constants::MY_XCODE_WORKSPACE_FILEPATH,
      device: Constants::MY_XCODE_TARGET_DEVICE_NAME,
      only_testing: Constants::MY_XCODE_TARGET_TESTS,
      sdk: 'iphonesimulator',
      scheme: 'DeviceSDK_iOS',
      xcpretty_args: '--no-utf',
      output_files: 'test-result.xml',
      output_types: 'junit',
      fail_build: true,
      clean: true
    )
  end
end