name: CI

on: 
  push: 
    branch: [main]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Bundle install
      run: bundle install
    - name: Pod install
      run: bundle exec pod install
    - name: Build and test
      run: bundle exec fastlane ios simulator_unit_tests
    - name: Swiftlint
      run: bundle exec fastlane lint
#    - name: Pod lib lint
#      run: pod lib lint
