name: iOS-Starter-Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  Tests:
    runs-on: macos-11
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.1.app/Contents/Developer
    steps:
    - uses: actions/checkout@v2
    - name: List
      run: xcrun simctl list
    - name: install pod
      run: pod install   
    - name: iOS UI Tests
      run: set -o pipefail && xcodebuild -workspace MyTestApp.xcworkspace -scheme "MyTestApp" -destination "platform=iOS Simulator,OS=latest,name=iPhone 11" clean test | xcpretty
